### ISSUE TITLE
TypeError: 'null' is not a function (evaluating 'jasmine.Ajax.requests.mostRecent().response

### ISSUE THREAD

**Issue by cliren** [IDCubed/karma-jasmine-ajax#5]
//code

jasmine.Ajax.requests.mostRecent().response({
      'status': 200,
      'responseText': data
    });

The following error is thrown with using latest (2.99.0) jasmine-ajax. Works fine with jasmine-ajax@2.0.2

```
TypeError: 'null' is not a function (evaluating 'jasmine.Ajax.requests.mostRecent().response({
          'status': 200,
          'responseText': data
        })')
```

**Comment by pdeegan** [comment]
Hi, sorry about the delay, please see #9 and #10 to see if this recent merge fixed your issue.  Otherwise, I'm happy to merge pull requests.  Thanks!

**Comment by jmunsch** [comment]
It looks like https://github.com/IDCubed/karma-jasmine-ajax/issues/9 and https://github.com/IDCubed/karma-jasmine-ajax/pull/10 to replace
 `response` with  `respondWith` works?

```
jasmine.Ajax.requests.mostRecent().respondWith({
    'status': 200,
    'responseText': data
});
```

Thanks.

**Comment by archirex** [comment]
Can you update the documentation as well? It threw me off here: http://jasmine.github.io/2.0/ajax.html?spec=mocking%20ajax%20suite%20wide%20usage%20allows%20responses%20to%20be%20setup%20ahead%20of%20time
